-- Seed products for Apex Perfumes
-- Execute this script in your Neon console after applying schema.sql

-- Insert products
INSERT INTO public.products (
  id,
  name,
  brand,
  price,
  original_price,
  images,
  category,
  type,
  notes,
  longevity,
  sillage,
  rating,
  stock,
  description,
  is_new,
  is_best_seller,
  is_on_sale,
  sizes,
  created_at,
  updated_at
) VALUES
(
  'inspired-1',
  'Cool Water',
  'Inspired',
  1199.00,
  NULL,
  ARRAY['https://wnaxppdlvfcfeluxlvxn.supabase.co/storage/v1/object/public/product-images/Cool-Water.png'],
  'men',
  'EDP',
  '{"top": ["Bergamot", "Cardamom"], "base": ["Amber", "Musk"], "heart": ["Oud", "Rose"]}'::jsonb,
  10,
  'strong',
  4.8,
  50,
  'Inspired by luxury oud fragrances',
  false,
  true,
  false,
  '{"20ml": {"label": "20 ml", "price": 349}, "50ml": {"label": "50 ml", "price": 599}, "100ml": {"label": "100 ml", "price": 799}}'::jsonb,
  '2025-11-11 10:15:21.080118+00',
  '2025-11-13 06:33:15.195882+00'
),
(
  'inspired-2',
  'Most Wanted',
  'Inspired',
  1199.00,
  NULL,
  ARRAY['https://wnaxppdlvfcfeluxlvxn.supabase.co/storage/v1/object/public/product-images/Most-Wanted.png'],
  'men',
  'EDP',
  '{"top": ["Citrus", "Spice"], "base": ["Vanilla", "Tonka"], "heart": ["Iris", "Leather"]}'::jsonb,
  9,
  'strong',
  4.7,
  50,
  'Inspired by intense noir fragrances',
  false,
  true,
  false,
  '{"20ml": {"label": "20 ml", "price": 349}, "50ml": {"label": "50 ml", "price": 599}, "100ml": {"label": "100 ml", "price": 799}}'::jsonb,
  '2025-11-11 10:15:21.080118+00',
  '2025-11-13 06:33:15.195882+00'
),
(
  'inspired-3',
  'Bleu De Chanel',
  'Inspired',
  1199.00,
  NULL,
  ARRAY['https://wnaxppdlvfcfeluxlvxn.supabase.co/storage/v1/object/public/product-images/Bleu-De-Chanel.png'],
  'men',
  'EDP',
  '{"top": ["Pineapple", "Blackcurrant"], "base": ["Oakmoss", "Vanilla"], "heart": ["Birch", "Jasmine"]}'::jsonb,
  10,
  'strong',
  4.9,
  50,
  'Inspired by legendary fruity fragrances',
  true,
  true,
  false,
  '{"20ml": {"label": "20 ml", "price": 349}, "50ml": {"label": "50 ml", "price": 599}, "100ml": {"label": "100 ml", "price": 799}}'::jsonb,
  '2025-11-11 10:15:21.080118+00',
  '2025-11-13 06:33:15.195882+00'
),
(
  'inspired-4',
  'Dior Sauvage',
  'Inspired',
  1199.00,
  NULL,
  ARRAY['https://wnaxppdlvfcfeluxlvxn.supabase.co/storage/v1/object/public/product-images/Dior-Sauvage.png'],
  'men',
  'EDT',
  '{"top": ["Bergamot", "Pepper"], "base": ["Ambroxan", "Cedar"], "heart": ["Lavender", "Geranium"]}'::jsonb,
  8,
  'moderate',
  4.6,
  50,
  'Inspired by wild fresh fragrances',
  false,
  false,
  false,
  '{"20ml": {"label": "20 ml", "price": 349}, "50ml": {"label": "50 ml", "price": 599}, "100ml": {"label": "100 ml", "price": 799}}'::jsonb,
  '2025-11-11 10:15:21.080118+00',
  '2025-11-13 06:33:15.195882+00'
),
(
  'inspired-5',
  'Gucci Flora',
  'Inspired',
  1199.00,
  NULL,
  ARRAY['https://wnaxppdlvfcfeluxlvxn.supabase.co/storage/v1/object/public/product-images/Gucci-Flora.png'],
  'women',
  'EDP',
  '{"top": ["Rose", "Peony"], "base": ["Musk", "Sandalwood"], "heart": ["Jasmine", "Lily"]}'::jsonb,
  9,
  'moderate',
  4.8,
  50,
  'Inspired by elegant rose fragrances',
  false,
  true,
  false,
  '{"20ml": {"label": "20 ml", "price": 349}, "50ml": {"label": "50 ml", "price": 599}, "100ml": {"label": "100 ml", "price": 799}}'::jsonb,
  '2025-11-11 10:15:21.080118+00',
  '2025-11-13 06:33:15.195882+00'
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  images = EXCLUDED.images,
  category = EXCLUDED.category,
  type = EXCLUDED.type,
  notes = EXCLUDED.notes,
  longevity = EXCLUDED.longevity,
  sillage = EXCLUDED.sillage,
  rating = EXCLUDED.rating,
  stock = EXCLUDED.stock,
  description = EXCLUDED.description,
  is_new = EXCLUDED.is_new,
  is_best_seller = EXCLUDED.is_best_seller,
  is_on_sale = EXCLUDED.is_on_sale,
  sizes = EXCLUDED.sizes,
  updated_at = now();
